### ISSUE TITLE
Errori dal log

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/mozitahub_bot#72]
Vi lascio degli stralci di un log da 500mb generato dal bot (non ve lo passo perchè sono tutti uguali):
```
[04-03-2021 15:39:55] Nessun nuovo Tweet. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telepot/loop.py", line 37, in run_forever
    self._handle(msg)
  File "/usr/local/lib/python3.7/dist-packages/telepot/helper.py", line 1041, in route
    return fn(msg, *args, **kwargs)
  File "./hub_mozita.py", line 403, in risposte
    user_id = msg['from']['id']
KeyError: 'from'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telepot/loop.py", line 37, in run_forever
    self._handle(msg)
  File "/usr/local/lib/python3.7/dist-packages/telepot/helper.py", line 1041, in route
    return fn(msg, *args, **kwargs)
  File "./hub_mozita.py", line 403, in risposte
    user_id = msg['from']['id']
KeyError: 'from'
[04-03-2021 15:49:55] Nessun nuovo Tweet. 
```

```
[07-03-2021 01:19:55] Nessun nuovo Tweet. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telepot/loop.py", line 60, in run_forever
    allowed_updates=allowed_updates)
  File "/usr/local/lib/python3.7/dist-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python3.7/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.7/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Gateway', 502, {'ok': False, 'error_code': 502, 'description': 'Bad Gateway'})
```

```
[09-03-2021 15:19:55] Nessun nuovo Tweet. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telepot/loop.py", line 67, in run_forever
    self._update_handler(update)
  File "/usr/local/lib/python3.7/dist-packages/telepot/loop.py", line 154, in <lambda>
    collectloop.input_queue.put(_extract_message(update)[1]))
  File "/usr/local/lib/python3.7/dist-packages/telepot/loop.py", line 113, in _extract_message
    return key, update[key]
KeyError: None
```

Forse è il caso di usare una versione patchato di telepot? ditemi voi

**Comment by Mte90** [comment]
Abbiamo avuto ancora problemi, il log degli errori aveva raggiunto 1gb di immondizia come questa.
@Sav22999 @dag7dev menziono voi così vi ricordate di buttare un occhio

**Comment by Sav22999** [comment]
Il problema è che salva nel file sbagliato, in un giorno non si può raggiungere 1 gb

**Comment by dag7dev** [comment]
> Abbiamo avuto ancora problemi, il log degli errori aveva raggiunto 1gb di immondizia come questa.
> @Sav22999 @dag7dev menziono voi così vi ricordate di buttare un occhio

L'ideale sarebbe rifare il bot con l'altra libreria, così perlomeno il problema "libreria" non lo abbiamo, come avevamo originariamente previsto tempo fa.

**Comment by Mte90** [comment]
> Il problema è che salva nel file sbagliato, in un giorno non si può raggiungere 1 gb

Non in un giorno è il log del comando dopo giorni di esecuzione. Secondo me succede che per un motivo o per un altro le varie librerie non riescono a comunicare ne con twitter o telegram e quindi errori a manetta con crash del bot.

**Comment by Sav22999** [comment]
@Mte90 dovrebbe generare un file log per ogni giorno. Per qualche motivo non sta funzionando.

Non ho tempo, al momento, di verificare

**Comment by Sav22999** [comment]
È un problema dato dalla funzione dei tweet, apparentemente.
Io consiglio di disattivarla
@dag7dev
